name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Icarus Verilog
        run: sudo apt-get install -y iverilog

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run tests
        run: python -m pytest test/test_correctness.py::test_int_adder_chain_ii1 -vv
        #  run: python -m pytest test/test_correctness.py -v
